services:
  mqreawakened:
    image: ghcr.io/${GHCR_OWNER:-feroxfoxxo}/${GHCR_REPO:-mqreawakened}:latest
    container_name: mqreawakened
    restart: unless-stopped
    environment:
      - DEFAULT_USERNAME=${DEFAULT_USERNAME:-admin}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD:-admin123}
      - DEFAULT_EMAIL=${DEFAULT_EMAIL:-admin@example.com}
      - DEFAULT_GENDER=${DEFAULT_GENDER:-Male}
      - DEFAULT_DOB=${DEFAULT_DOB:-01-01-2000}
      - FORCE_REBUILD=${FORCE_REBUILD:-0}
      - SERVER_ADDRESS=${SERVER_ADDRESS:-localhost}
      - GAME_PORT=${GAME_PORT:-9339}
      - DOTNET_RUNNING_IN_CONTAINER=true
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${GAME_PORT:-9339}:9339"
    volumes:
      - ${DATA_HOST_PATH:-./Game/Data}:/data
      - ${GAME_ARCHIVES_PATH:-./Build/Archives}:/archives:ro
